"""added reset_tokens

Revision ID: 35be311d7bac
Revises: 8e69af4bd9d0
Create Date: 2024-09-02 15:10:52.020796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35be311d7bac'
down_revision = '8e69af4bd9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiration')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
